### ISSUE TITLE
[all-openwisp-repositories] Update the `openwisp-utils-qa-checks`

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-utils#63]
Thanks to @marfgold1 , now we have https://github.com/openwisp/openwisp-utils/pull/60 merged.

We can now remove multiple checks of `openwisp-utils-qa-checks` like this:

```
openwisp-utils-qa-checks --migration-path "./openwisp_users/migrations/ ./tests/testapp/migrations/" --migrations-to-ignore "3 2"
```
For this issue, you have to implement `openwisp-utils-qa-check` in all the openwisp repositories that use `openwisp-utils-qa-checks` multiple times to accomplish the same.

**Comment by waleko** [comment]
You can see the list of all PRs regarding to this issue above (all refernces to this issue) or below just as plaintext (if references don't work for some reason):

- [openwisp-controller](https://github.com/openwisp/openwisp-controller/pull/140)
- [netjsonconfig](https://github.com/openwisp/netjsonconfig/pull/144)
- [django-freeradius](https://github.com/openwisp/django-freeradius/pull/262)
- [django-netjsongraph](https://github.com/openwisp/django-netjsongraph/pull/107)
- [ansible-openwisp2](https://github.com/openwisp/ansible-openwisp2/pull/158)
- [django-ipam](https://github.com/openwisp/django-ipam/pull/87)
- [openwisp2-docs](https://github.com/openwisp/openwisp2-docs/pull/92)
- [django-loci](https://github.com/openwisp/django-loci/pull/42)
- [django-owm-legacy](https://github.com/openwisp/django-owm-legacy/pull/4)
- [netdiff](https://github.com/openwisp/netdiff/pull/79)
- [openwisp-network-topology](https://github.com/openwisp/openwisp-network-topology/pull/46)
- [openwisp-users](https://github.com/openwisp/openwisp-users/pull/94)
- [openwisp-radius](https://github.com/openwisp/openwisp-radius/pull/74)
- [openwisp-config](https://github.com/openwisp/openwisp-config/pull/99)

Some PRs have travis failing. I've explained the reasons, why it happens. Mostly it is just absence of endlines or too long lines in some files. On the other hand, `openwisp-network-topology` and `openwisp-radius` builds **are failing because of some dependencies issues** as described in [the PR comment](https://github.com/openwisp/openwisp-network-topology/pull/46#issuecomment-570285023).

**Comment by atb00ker** [comment]
I think we should do https://github.com/openwisp/openwisp-utils/issues/53 before merging these, what do you think? :smile:

**Comment by marfgold1** [comment]
Yeah we should have wait for #53 first so we are not change all of these again

**Comment by nemesisdesign** [comment]
django-netjsonconfig seems missing

**Comment by nemesisdesign** [comment]
Done, thank you all!
